---
title: "ERA 5 Gap Filling quality Assessment"
output: html_notebook
---

```{r, include = F}
library(tidyverse)
theme_set(theme_bw())
library(Metrics)
library(lubridate)
library(xfun)
devtools::load_all()
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
meteo_vars <-
  list(
    "Tair" = "TA_F",
    "SW_IN" = "SW_IN_F",
    "LW_IN" = "LW_IN_F" ,
    "VPD" = "VPD_F",
    "P" = "P_F",
    "PA" = "PA_F"
  )

meteo_vars_eta <- names(meteo_vars) %>%
        paste0("_ERA")

hai_era_path <- here::here("data/FLX_DE-Hai_FLUXNET2015_ERAI_HH_1989-2014_1-4.csv")
hai_path <- here::here("data/FLX_DE-Hai_FLUXNET2015_FULLSET_HH_2000-2012_1-4.csv")
site_raw <- read_csv(hai_path, col_types = cols(TIMESTAMP_START = col_datetime(format="%Y%m%d%H%M"), TIMESTAMP_END = col_datetime(format="%Y%m%d%H%M")), na = c("-9999", "-9999.99"))

# Remove gap filled measurements
site_obs <- site_raw %>%
        filter((if_all(as.character(meteo_vars), \(x) {
          name <- cur_column()
          cur_data()[str_glue("{name}_QC")] == 0
        }))) %>%
        select(TIMESTAMP_END, !!!meteo_vars)

site_era <- read_csv(hai_era_path, col_types = cols(TIMESTAMP_START = col_datetime(format="%Y%m%d%H%M"), TIMESTAMP_END = col_datetime(format="%Y%m%d%H%M")), na = c("-9999", "-9999.99")) %>%
        rename(Tair_ERA = TA_ERA) %>%
        select(TIMESTAMP_END, !!!meteo_vars_eta)

site <- site_obs %>%
        left_join(site_era, by = "TIMESTAMP_END")
```

```{r}
# calculate RMSE for each variable
walk(seq_along(meteo_vars), function(i){
  var_name <- sym(names(meteo_vars)[[i]])
  var_name_era <- sym(paste0(var_name, "_ERA"))
  site <<- site %>%
          mutate(
                  "{var_name}_err" := !!var_name - !!var_name_era
          )
})

# more tidyversy version, but a bit slower
# site %>%
#   mutate(across(
#     names(meteo_vars),
#     \(x) {
#       var_name <- cur_column()
#       x - cur_data()[paste0(var_name, "_ERA")]
#     },
#     .names = "{.col}_err"
#   ))

site_stat <- site %>%
        summarize(
          across(ends_with("err"),
              list( rmse = ~sqrt(mean(.x ^ 2)))
        ))
```

## Tair

```{r, results = 'asis', message = FALSE, echo=FALSE}
knit_template("analysis/fragments/variable_assess_ERA_gapfilling.rmd", var = "Tair", unit="°C")
```

## SW_IN

```{r, results = 'asis', echo = FALSE}
knit_template("analysis/fragments/variable_assess_ERA_gapfilling.rmd", var = "SW_IN", unit="W m-2")
```
## VPD


```{r, results = 'asis',  echo = FALSE}
knit_template("analysis/fragments/variable_assess_ERA_gapfilling.rmd", var = "VPD", unit="hPa")
```

## P

```{r, results = 'asis',  echo = FALSE}
knit_template("analysis/fragments/variable_assess_ERA_gapfilling.rmd", var = "P", unit="mm")
```


## PA


```{r, results = 'asis',  echo = FALSE}
knit_template("analysis/fragments/variable_assess_ERA_gapfilling.rmd", var = "PA", unit="hPa")
```